# Generated by Django 5.1.5 on 2025-01-23 16:06

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_name", models.CharField(max_length=225)),
                ("description", models.CharField(max_length=128)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Incomplete", "Incomplete"),
                            ("Complete", "Complete"),
                        ],
                        default="Incomplete",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
